name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  #job name
  check-application:
    runs-on: ubuntu-latest
    # #permite que seja possivel testar em multiplas versoes
    # strategy:
      # matrix:
      #   go: ['1.14', '1.15']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
          # go-version: ${{ matrix.go }}
      - name: Test cases
        working-directory: go
        run: go test
      - name: Test math.go File
        working-directory: go
        run: go run math.go


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: matheusnachtigall/fc2.0-ci-go:latest