name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  #job name
  check-application:
    runs-on: ubuntu-latest
    strategy:
      #permite que seja possivel testar em multiplas versoes
      matrix:
        go: ['1.14', '1.15']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go